### ISSUE TITLE
深入理解 CSS 选择器、优先级与内联样式 [AI]

### ISSUE THREAD

**Issue by zyx190** [zyx190/GmeekBlog#7]
CSS（Cascading Style Sheets，层叠样式表）是用于控制网页视觉表现的关键技术之一。在编写 CSS 时，理解选择器、优先级和内联样式之间的关系至关重要；这篇文章将详细讲解这些概念，帮助你在项目中更好地管理样式。

### 元素选择器
元素选择器用于选择所有指定类型的 HTML 元素。例如，选择所有 `<p>` 标签：

```css
p {
  color: blue;
}
```

### 类选择器
类选择器用于选择具有特定类名的元素，类名前用 `.` 表示。例如，选择所有 class="btn" 的元素：

```css
.btn {
  background-color: green;
}
```

### ID 选择器
ID 选择器用于选择具有特定 ID 的元素，ID 前用 `#` 表示。例如，选择 ID="header" 的元素：

```css
#header {
  font-size: 24px;
}
```

### 属性选择器
属性选择器用于选择具有特定属性的元素。例如，选择所有 type="text" 的 `<input>` 元素：

```css
input[type="text"] {
  border: 1px solid black;
}
```

### 伪类选择器
伪类选择器用于选择处于特定状态的元素。例如，选择当鼠标悬停时的元素：

```css
a:hover {
  color: red;
}
```

### 伪元素选择器
伪元素选择器用于选择元素的一部分。例如，在元素内容前插入内容：

```css
p::before {
  content: "Note: ";
  font-weight: bold;
}
```

## 2. CSS 优先级
在处理多个选择器时，CSS 优先级决定哪个样式将生效。优先级通过以下规则计算：

### 优先级规则
1. **内联样式**：`1000`
2. **ID 选择器**：`100`
3. **类选择器、伪类选择器、属性选择器**：`10`
4. **元素选择器、伪元素选择器**：`1`
5. **通配符选择器** (`*`) 和组合选择器（如子代选择器）没有特定优先级。

### 优先级示例
```css
/* 优先级 1 */
p {
  color: red;
}

/* 优先级 10 */
.text {
  color: blue;
}

/* 优先级 100 */
#intro {
  color: green;
}
```

如果在一个元素上同时应用了上述样式，最终颜色将是绿色，因为 ID 选择器的优先级最高。

## 3. `!important` 强制应用样式
`!important` 是一个特殊标记，它可以让特定的 CSS 规则强制生效，无论其他规则的优先级如何。例如：

```css
p {
  color: red !important;
}
```

即使有其他选择器设置了颜色，只要没有使用 `!important`，红色将被优先应用。`!important` 应谨慎使用，因为它可能导致样式管理变得混乱。

## 4. 内联样式
内联样式直接在 HTML 元素的 `style` 属性中定义，优先级最高。例如：

```html
<p style="color: yellow;">Hello World</p>
```

即使有其他外部或内部样式表中的样式规则，内联样式也会覆盖它们，除非那些规则使用了 `!important`。

## 5. 选择器的结合使用
通过组合多个选择器，可以进一步提高优先级。例如：

```css
/* 优先级 2 */
div p {
  color: red;
}

/* 优先级 20 */
.container .text {
  color: blue;
}
```

在这种情况下，`.container .text` 的优先级比 `div p` 高，因此蓝色会覆盖红色。

## 6. 层叠性与顺序
CSS 的层叠性意味着当多个样式规则作用于同一元素时，优先级高的样式生效。如果优先级相同，则后定义的规则覆盖前定义的规则。

## 结论
理解 CSS 选择器、优先级、`!important` 和内联样式之间的关系是编写高效、可维护的样式表的关键。掌握这些概念，你将能够更好地控制网页元素的视觉表现，避免不必要的样式冲突和意外行为。

---

Title: 深入理解 CSS 选择器、优先级、!important 与内联样式
Date: 2024-08-30
Author: ChatGPT
